name: woopra-plugin CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '21.3.1'
          java: 'java11'
      - name: Install native-image component
        run: |
          gu install native-image
      - name: Build native application
        run: |
          ./mvnw --settings settings.xml clean package -Pnative -DskipTests
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
      - name: Build image
        run: |
          docker build -t quay.io/${ORGANIZATION}/devworkspace-telemetry-woopra-plugin:${TAG} -f src/main/docker/Dockerfile.native .
        env:
          ORGANIZATION: eclipse
          TAG: latest
      - name: set LATEST_IMAGE environment variable
        run: echo "LATEST_IMAGE=quay.io/${ORGANIZATION}/devworkspace-telemetry-woopra-plugin:${TAG}" >> $GITHUB_ENV
        env:
          ORGANIZATION: eclipse
          TAG: latest
      - name: set SHA_IMAGE environment variable
        run: echo "SHA_IMAGE=quay.io/${ORGANIZATION}/devworkspace-telemetry-woopra-plugin:${GITHUB_SHA:0:7}" >> $GITHUB_ENV
        env:
          ORGANIZATION: eclipse
      - name: tag SHA_IMAGE
        run: docker tag $LATEST_IMAGE $SHA_IMAGE
      - name: Log into docker registry
        run: docker login ${REGISTRY} -u ${USERNAME} -p ${PASSWORD}
        env:
          REGISTRY: quay.io
          USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Push image latest
        run: docker push $LATEST_IMAGE
        env:
          ORGANIZATION: eclipse
          TAG: latest
      - name: Push image sha
        run: docker push $SHA_IMAGE
        env:
          ORGANIZATION: eclipse
          TAG: ${GITHUB_SHA:0:7}